### ISSUE TITLE
Slimbook error while opening

### ISSUE THREAD

**Issue by shaunegaming** [slimbook/slimbookintelcontroller#10]
I recently downloaded slimbook to see if i could increase the tdp limit  so that it could run better but i keep on getting this error . I've Tried python Version 2.7 ,3 and 3.8 with the same error 

```SlimbookIntelController-Applyconfig, executed as: shaune

Homedir: /home/shaune

/usr/share/slimbookintelcontroller/src/slimbookintelcontroller-autostart.desktop
/home/shaune/.config/autostart/slimbookintelcontroller-autostart.desktop
model name	: Intel(R) Pentium(R) Silver N5030 CPU @ 1.10GHz
Traceback (most recent call last):
  File "/usr/share/slimbookintelcontroller/src/slimbookintelcontroller.py", line 51, in <module>
    version = patron.search(cpu).group(1)
AttributeError: 'NoneType' object has no attribute 'group'```

**Comment by MarSlimbook** [comment]
Slimbook Intel controller was designed for Intel Core i(x) processors, so I'm afraid your processor is not supported. You could try using [kitsunyan/intel-undervolt](https://github.com/kitsunyan/intel-undervolt) directly if you have a Haswell or newer CPU.
