### ISSUE TITLE
Slimbook Intel Controller things secure boot is enabled while it is not

### ISSUE THREAD

**Issue by smumriak** [slimbook/slimbookintelcontroller#5]
Hi,
I've just installed slimbook intel controller together with slimbook battery on pop!_os 21.04. When i try to save settings i get the message saying "this computer has secure boot enabled which does not allow kernel to manage cpu parameters". I double checked EFI settings to ensure it's off. Also `mokutil --sb-state` returns "SecureBoot disabled". 
Trying on Framework laptop with Intel i7-1165G7

**Comment by slimbook** [comment]
Hi, thanks for reporting this bug, the new version (0.3beta) should fix that (it should be available today)

**Comment by lbkNhubert** [comment]
Thank you for your work on this. I'm running 0.3 beta and seeing the same issue, also on a Framework i7-1165G7. Happy to test anything or pull any logs that might help.

**Comment by hakimzulkufli** [comment]
I'm having the same issue on a HP Zbook 15 G4 (BIOS ver 1.39) even with 0.3beta installed.
In BIOS, Secure Boot is set to: "Legacy Disabled and Secure Boot Disabled".

Output of `bootctl status`:
```
❯ bootctl status
systemd-boot not installed in ESP.
System:
     Firmware: n/a (n/a)
  Secure Boot: disabled
   Setup Mode: user
 TPM2 Support: yes
 Boot into FW: supported
```

Logs from `slimbookintelcontroller` tells me that my `processor is not found in list`.
Perhaps this is why the error occurred? (I'm in the process of configuring the table for my CPU on my own.)
```
❯ slimbookintelcontroller
A
/usr/share/slimbookintelcontroller/src
SlimbookIntelController-Applyconfig, executed as: izanami
izanami
Homedir: /home/izanami

/usr/share/slimbookintelcontroller/src/slimbookintelcontroller-autostart.desktop
/home/izanami/.config/autostart/slimbookintelcontroller-autostart.desktop
model name	: Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
CPU | Model: 'i7-7820HQ' | Version: i7 | CPU Numbers: 7820 | CPU Letters: HQ.
File .conf already exists

[CONFIGURATION]
mode = medium
autostart = on
show-icon = on
cpu = 

[PROCESSORS]
i3-10110u = 10@12/12@18/15@28/ 10/15/25/ w
i3-1005g1 = 10@12/12@18/15@28/ 13/15/25/ w
i5-8250u = 10@12/12@18/15@28/ 10/15/25/ w
i5-8265u = 10@12/12@18/15@28/ 10/15/25/ w
i5-10210u = 10@12/12@18/15@28/ 10/15/25/ w
i5-1035g1 = 10@12/12@18/15@28/ 13/15/25/ w (essential)
i7-7500u = 10@12/12@18/15@28/ 7.5/15/25/ w (excalibur)
i7-8550u = 10@12/12@18/15@28/ 10/15/25/ w
i7-8565u = 10@12/12@18/15@28/ 10/15/25/ w
i7-10510u = 10@12/12@18/15@28/ 10/15/25/ w
i7-10750h = 35@40/40@45/45@54/ 35/45/54/ w (prox 15)
i7-10875h = 35@40/40@45/45@54/ 35/45/54/ w (?)
i7-1165g7 = 10@12/12@18/15@30/ 12/15/28/ w (executive)

Found thermal zone!
Found thermal zone!
Found thermal zone!
Found thermal zone!
Found thermal zone!
Found thermal zone!
0.3beta

- Autostart enabled
- Indicator enabled
- Medium
Processor not found in list
WARN dialog closed by clicking CLOSE button
```

slimbookintelcontroller 0.3beta (installed from [AUR](https://aur.archlinux.org/packages/slimbookintelcontroller/))
Arch Linux (linux-zen 5.15.2-zen1-1-zen)
Intel i7-7820HQ

**Comment by MarSlimbook** [comment]
try installing mokutil, I have to add it as adependency

**Comment by hakimzulkufli** [comment]
@MarSlimbook

>Try installing mokutil, I have to add it as a dependency, I'll update as soon as I confirm the solution.
Can confirm. Installing `mokutil` fixes the Secure Boot error.

>How did you do it? could you send the configuration file?
To be clear, I was trying to see if unsupported CPU could cause the Secure Boot error as well but it didn't.
Here's my config:

```
CONFIGURATION]
mode = low
autostart = on
show-icon = on
cpu = i7-7820HQ

[PROCESSORS]
i3-10110u = 10@12/15@25/20@30/ 10/15/25/ w
i3-1005g1 = 10@12/15@25/20@30/ 13/15/25/ w
i5-8250u = 10@12/15@20/20@35/ 10/15/25/ w
i5-8265u = 10@12/15@20/20@35/ 10/15/25/ w
i5-10210u = 10@12/15@20/20@30/ 10/15/25/ w
i5-1035g1 = 10@12/15@20/20@35/ 13/15/25/ w
i7-7500u = 10@12/15@20/20@35/ 7.5/15/25/ w
i7-8550u = 10@12/15@25/30@45/ 10/15/25/ w
i7-8565u = 10@12/15@25/30@45/ 10/15/25/ w
i7-1065g7 = 10@12/15@20/25@45/ 12/15/25/ w
i7-10510u = 10@12/15@25/30@50/ 10/15/25/ w
i7-10750h = 15@20/30@45/54@70/ 35/45/54/ w
i7-1165g7 = 10@12/15@25/30@50/ 12/15/28/ w
i7-7820hq = 10@12/15@25/30@45/ 25/35/45/ w
```

It's mostly based on the `i7-10750h` profile since both have the same TDP and TDP down.
I'm not sure if it's working properly since there isn't a useful monitoring tool on Linux that I'm aware of like HWiNFO64 on Windows.

**Comment by slimbook** [comment]
Seems that now it's getting your conf values, have you tested intel-undervolt:
Usage: undervolt ${index} ${display_name} ${undervolt_value}
Example: undervolt 2 'CPU Cache' -25.84

You might be able to undervolt this:
undervolt 0 'CPU' 0
undervolt 1 'GPU' 0
undervolt 2 'CPU Cache' 0
undervolt 3 'System Agent' 0
undervolt 4 'Analog I/O' 0

You can go to [kitsunyan/intel-undervolt](https://github.com/kitsunyan/intel-undervolt), the config file is /etc/intel-undervolt.conf
We are open to add functionalities, if you find something you'd like us to implement, just tell us.

**Comment by hakimzulkufli** [comment]
I would request to add undervolt support from within `slimbookintelcontroller` itself but my laptop's BIOS doesn't allow changing the voltage so I can't test it.

For now, `slimbookintelcontroller` is able to change the power package limit, which my laptop allows and that is good enough.

**Comment by KevinA410** [comment]
> Try installing mokutil, I have to add it as a dependency, I'll update as soon as I confirm the solution.
> 
> > No difference after configuring my own CPU.
> 
> @hakimzulkufli, How did you do it? could you send the configuration file?

thanks a lot!, it works well for me.
