### ISSUE TITLE
10th gen intel processor not supported

### ISSUE THREAD

**Issue by AlexandreAndrade00** [slimbook/slimbookintelcontroller#6]
Hi,
I have i7 10710u in my laptop, and is the unique 10th gen intel processor not natively supported by the software.

**Comment by slimbook** [comment]
We will add it in the next version, at the moment, you can add it by your own in the configuration file /home/(username)/.config/slimboookintelcontroller/slimbookintelcontroller.conf you can use the following values as an example:

> i7-10710U = 10@12/12@18/15@28/ 10/15/25/ w

You just have to add the line to the processors section, by the way, we are improving the TDP values setting in the next version. 
I hope this answer has been helpful, don't hesitate to ask if you need something else.
Regards

**Comment by AlexandreAndrade00** [comment]
Thanks!
